### PR TITLE
multiple population size by 10

### PR DESCRIPTION
**Pull request by sbfnk**
to see what it does to the sessions

### CODE REVIEW

**Comment by sbfnk** [comment]
Output can be downloaded at https://github.com/nfidd/nfidd/actions/runs/9579898985?pr=128

image

**Comment by sbfnk** [comment]
rebasing to PR branch for nowcasting

**Comment by sbfnk** [comment]
This now looks "better" in the sense that the better motivated models do better at nowcasting. I'm happy to go ahead with this. @seabbs sound good?

We'll have to carefully go through the earlier sessions as there might be some hardcoded population sizes in there.

**Review by seabbs — COMMENTED** [review]
Agree

**Review by seabbs — APPROVED** [review]

**Pull request merged**
