### PR TITLE
use epiforecasts universe instead of github

### LINKED ISSUE #364: pull in qra / stackr from epiforecasts universe?
I've updated https://epiforecasts.r-universe.dev/ to only use releases. We could use this instead of the github versions for qra and stackr.

### PR DESCRIPTION
**Pull request by sbfnk**
closes #364

### CODE REVIEW

**Review by seabbs — APPROVED** [review]
LGTM

**Comment by seabbs** [comment]
Failure is finding `qra`

**Comment by seabbs** [comment]
I don't see a clear reason for that as `qra` has a release and the function obviously is present

**Comment by sbfnk** [comment]
some temporary r-universe glitch now due to package renaming which hopefully will be resolved in one of the upcoming hourly rebuilds

**Review by seabbs — APPROVED** [review]

**Pull request merged**
