### PR TITLE
Remove last slide laptop graphic

### LINKED ISSUE #301: Last slide of some lectures has formatting issue
When rendered the last slide Your turn header sometimes has a formatting problem with showing the laptop graphic thing 

Affects slides: nowcasting, joint nowcasting, forecasting as an epi problem, forecasting models

Doesn't affect slides: biases, convolutions, intro to Rt

image

### PR DESCRIPTION
**Pull request by kathsherratt**
If others have it working fine then of course just close this!

This closes #301 -  I don't know why it renders on some slide decks and not others and no luck working it out. So as a first suggestion for time reasons, just removing (everywhere for consistency.).

### CODE REVIEW

**Comment by sbfnk** [comment]
I think it's because inline R when rendering to revealjs needs `engine: knitr` in the YAML header

Don't feel strongly whether we should we keep the laptop icon or not - but if we remove everywhere should we also remove the `engine:knitr` statements on the slides that have them? If I remember correctly that was the reason I put them in in the first place.

**Comment by seabbs** [comment]
In #308 I added a bunch of engine: knitr statements. Does this fix it?

**Comment by sbfnk** [comment]
Closing as superseded by #308

**Comment by sbfnk** [comment]
> In https://github.com/nfidd/nfidd/pull/308 I added a bunch of engine: knitr statements. Does this fix it?

It should (let's double check)

**Comment by kathsherratt** [comment]
yes fixed thanks!

**Pull request closed without merging**
