### PR TITLE
Add Rt plot and fix forecasting plot

### PR DESCRIPTION
**Pull request by seabbs**
I think this fixes the plotting. Also adds a Rt plot. Changes the prior on the AR model as I think this is more reasonable.

### CODE REVIEW

**Comment by seabbs** [comment]
@zsusswein do you think this fixes the plotting issue? 
@kathsherratt I need to go and get on the plane. Could you check our plotting as I think this is a bit of a killer issue! 

If anyone gets the chance I think the AR model should really be doing better than it is score wise. I think this is due to priors? If anyone can investigate and set new ones + update all the fits in data-raw and see if that makes a difference in the session I think that would be great

**Comment by seabbs** [comment]
If not I will try and do that on Monday but it will be difficult communicating why things have changed with participants

**Review by zsusswein — APPROVED** [review]
>  do you think this fixes the plotting issue?

LGTM 

image

**Comment by zsusswein** [comment]
You might also want to link #259

**Comment by seabbs** [comment]
Okay to merge @kathsherratt?

**Review by kathsherratt — APPROVED** [review]

**Pull request merged**
