### PR TITLE
Forecasting concepts - suggestions

### PR DESCRIPTION
**Pull request by kathsherratt**
mainly adding titles to plots & typos

just seen part overlap with #150 but doesn't conflict.

### CODE REVIEW

**Comment by seabbs** [comment]
Due to the use of squash commits this will have a very messy merge life. I'd suggest waiting until we merge in forecasting concepts and do as a supplement?

**Comment by kathsherratt** [comment]
Yes agree, just making suggestions while I was working through it - we'll just come back to this when the session is more final.

**Comment by seabbs** [comment]
I think we can wake this back up now? Sorry lots of merge issues and stuff

**Comment by kathsherratt** [comment]
No problem at all I'll have another look shortly

**Review by seabbs — APPROVED** [review]
Very nice

**Pull request merged**
