### PR TITLE
add mixture ensembles

### PR DESCRIPTION
**Pull request by sbfnk**
I think it makes a nice addition for the "full" version but it makes an already quite complicated session even more complicated. Perhaps something we want to cut again when thinking about this for a 60 minute session.

### CODE REVIEW

**Review by seabbs — APPROVED** [review]
From a site read this looks great. I agree for Idm we will need to think about timing. I see an install error on deployment that looks to be coming from Stacie

**Comment by sbfnk** [comment]
Yes, and I don't really understand it. Am investigating on the side as not a priority for now.

**Comment by seabbs** [comment]
I had a look and I don't either unless it's something super obvious like a misnamed model being imported by restan which seems unlikely

**Comment by sbfnk** [comment]
Turned out this fixed it. Not sure how this ended up in Rbuildignore. 

https://github.com/epiforecasts/stackr/commit/1853faf5a27df948706b229bb358f9ea268c7d24

**Comment by seabbs** [comment]
I'm on my phone so can't resolve merge issues but otherwise this looks good

**Pull request merged**
