### PR TITLE
Downsample (more) plots

### PR DESCRIPTION
**Pull request by kathsherratt**
extends #256 following [confirmation of on odd ones out](https://github.com/nfidd/nfidd/pull/256#issuecomment-2185175960)

### CODE REVIEW

**Comment by seabbs** [comment]
@kathsherratt see #263 for a potential killer issue with sample!

**Review by seabbs — APPROVED** [review]

**Comment by seabbs** [comment]
Any idea what the website building issue is here?

**Comment by seabbs** [comment]
It looks like a missing pipe?

**Comment by kathsherratt** [comment]
thanks for the spot and the fix!

**Pull request merged**
